services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - /var/share:/media
    restart: unless-stopped
